### PR TITLE
Updates Rails parameter to expected syntax

### PR DESCRIPTION
**Pull request by os6sense**

### CODE REVIEW

**Comment by alaibe** [comment]
does that require update on our projects?

**Comment by os6sense** [comment]
Should bed pulled automatically when running on circle ci; This was enabled originally for projects so I cant be sure if there will be any cop warnings but they *should* be fixed anyways

**Comment by alaibe** [comment]
My concerns is that this change has been introduced I think in a different version of rubocop that we are using
So shall we update the rubocop version on each project?

**Comment by os6sense** [comment]
Ahhh I see your point - members-epic is currently failing since it is using 0.40 vs 0.35.1 so probably worth doing this and upgrading on a project by project basis.

**Comment by alaibe** [comment]
If the gem as been updated that is why
The gemfile should look like this:
`gem 'rubocop', '~> 0.34.0', require: false`

If not feel free to update

**Comment by alaibe** [comment]
(there is another ticket about updating rubocop)
And actually it will requires more changes
So I close this one  👎

**Comment by os6sense** [comment]
True; probably worth updating it to 0.40 at some point but yes, while we are rushed worth just doing the change in members epic

**Pull request closed without merging**
