### PR TITLE
For discussion? Added the thoughtbot rubocop yml file with …

### PR DESCRIPTION
**Pull request by os6sense**
…modifications not to nag about the use of single quotes.

I've been using rubocop for a while as a way to provide a check on the consistency of my coding style, and rather than spamming the channels with questions about it I was wondering how people feel about this. Pretty basic stuff such as consistent use of whitespace characters, line length etc.

Also as I edit a file I tend to make minor fixes based on the rubocop warnings and I don't want to do this if  its going to be out of sync with everyone else's style preferences - that said I've seen only the expected warnings in general when working with it enabled.

With the fact that we're growing this might be useful even if optional?

### CODE REVIEW

**Comment by sambarton** [comment]
For the record I am a big fan of clean and consistent formatting. It has nothing to do with being too detailed, it is just good practice. I have been on the receiving end of bad YML and had to manually fit it so more than happy to include something to maintain best practice. 

This is one of those good ideas that should go to the floor, see what the chaps think. Don't just use the first option that comes along for the purpose of applying a good idea.

**Comment by alaibe** [comment]
Rubocop is definitively on the todo list, we just need to build the configuration. and apply it to every project and CI. 
Here is the todo list to integrate with rubocop:
- create a yml which follow the guide
- add rubocop to every project
- add rubocop to the circle ci process

This is not a 5mn job, that s just why it hasn't been done yet but definitively on the list

**Comment by os6sense** [comment]
* create a yml which follow the guide

This is the thoughtbot yml so it *should* be as close to the guide as possible. I've changed just one setting which was bringing up a lot of errors in existing code. That said theres a couple that I wouldn't mind seeing changing. We could possibly scratch that off the todo list.

I'd spend some time manually running rubocop (or integrating it with your editor) before adding it to the projects/circleci since there would be an intimidating number of errors and I find slowly working through a project as its updated is far less work than trying to do everything en mass.

**Comment by alaibe** [comment]
:+1:

**Pull request merged**
