### PR TITLE
Update vertical alignment

### PR DESCRIPTION
**Pull request by alaibe**

### CODE REVIEW

**Comment by cheba** [comment]
Is this for the following?
```ruby
a   = 1
bar = 2
```

**Comment by alaibe** [comment]
Yes the one you just discuss on https://github.com/smartpension/cms/pull/11

**Comment by cheba** [comment]
Well, my position is clear, I guess.

:hankey:

**Comment by os6sense** [comment]
I think style/alignment conversations such as this are very very subjective. *Personally* poor alignment bugs the hell out of me and I find aligned lines easier to scan/read (and sometimes to spot the more obvious typos).

**Comment by os6sense** [comment]
:+1: from me then

**Comment by cheba** [comment]
@os6sense I agree that it's subjective. But once can argue that the following is a poor alignment:
```ruby
a      = 1
```

**Comment by alexdesi** [comment]
:+1:

**Comment by alaibe** [comment]
I just look at https://github.com/bbatsov/ruby-style-guide and he does not align like that in his guide too.

 :-1:  for me

**Comment by NelsonMorales** [comment]
:+1:

**Pull request merged**
